version: '3.3'

volumes:
  db_data:

services:
  database:
    image: mysql:8.0.25
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cine
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuser
    networks:
      - cine-net

  server:
    container_name: cine-server
    build: .
    depends_on:
      - database
    ports:
      - "9080:8080"
    restart: always
    networks:
      - cine-net

networks:
  cine-net:
